version: 0.2
phases:
  build:
    commands:
      - rake config:codebuild BRANCH=master
      - rake clean:orphans
artifacts:
  name: $(date +%Y%m%d%H%M%S)-resources-cleanup.zip
  files:
    - "out/**/*"
  discard-paths: no
