version: 0.2
env:
  shell: bash
  git-credential-helper: yes
phases:
  build:
    commands:
      - rake config:codebuild
      - rake deploy:analytics:$TARGET_ENVIRONMENT
artifacts:
  name: $(date +%Y%m%d%H%M%S)-deploy-analytics-$($TARGET_ENVIRONMENT)
  files:
    - "out/**/*"
  discard-paths: no
