version: 0.2
phases:
  build:
    commands:
      - rake test:build_system
      - rake lint:terraform
      - rake validate:static
      - rake validate:tier-metadata
      - rake validate:local_messages
      - rake plan:ci
      - rake plan:analytics:ci
      - rake plan:pubdash:ci
artifacts:
  name: $(date +%Y%m%d%H%M%S)-$(echo $CODEBUILD_SOURCE_VERSION | sed -e 's;/;-;g').zip
  files:
    - "out/**/*"
  discard-paths: no
